### ISSUE TITLE
proposal needs more detail

### ISSUE THREAD

**Issue by tofr** [LargeLlama/Shqiperi#1]
How will term 2 concepts be employed?

**Comment by LargeLlama** [comment]
Term 2 concepts will be employed in the maze generation, which employs the use of a binary tree. We will also use various collections to store the players inventory, as well as store the time in which attacks/moves are done. This will be added to the proposal accordinly, and the issue when be closed when this happens.

**Comment by LargeLlama** [comment]
Done! See recent commit for more detail
